### ISSUE TITLE
More detailed documentation on output JSON?

### ISSUE THREAD

**Issue by mihirbpi** [bagherilab/CARCADE#1]
I was looking into using your software to model CAR T cells and was wondering if you had more detailed documentation on the output JSON files and what the output represents. 

For example, in the example output JSONs there is a cells entry at each time step that contains some arrays and I was wondering where I could find more info on what those arrays represent. I have attached an image of what I am looking at in the output JSONS:

<img width="643" alt="Screen Shot 2022-06-30 at 1 04 46 PM" src="https://user-images.githubusercontent.com/31811437/176768755-e83477bf-741a-4269-9823-9e1b0c912b53.png">

The README.md in the docs folder says that the JSONs represent the outputs of the various profilers but does not go into what those profilers output and what it represents in more detail. Is there anywhere I can find this information?

**Comment by aprybutok** [comment]
Thank you @mihirbpi for raising this issue! I will work on adding documentation to the profiler javadocs. In the mean time, you can refer to the original ARCADE paper's supplement for a description of the structure of the growth profiler:

J Yu and N Bagheri. (2020). Agent-based models predict emergent behavior of heterogeneous cell populations in dynamic microenvironments. Frontiers in Bioengineering and Biotechnology. doi: 10.3389/fbioe.2020.00249. https://doi.org/10.3389/fbioe.2020.00249

Note, the original paper only included tissue cells, so the structure of the parameter lists in the parameter profiler are slightly out of date and do not contain a description for the CAR T-cells. 

I will work on this update for the CARCADE repo. Thanks for bringing this up and taking an interest in the code!

**Comment by mihirbpi** [comment]
Hi! Thanks for the response. I took a look at the supplement and the documentation for the JSON and it helps a bit. It would be great if you could provide more detailed documentation specific to CARCADE in the Github repo itself at some point though

**Comment by aprybutok** [comment]
@mihirbpi There will be! There is already a branch to work on the update in progress and it should be merged shortly after peer review, which has already been requested via a pull request. The javadocs for each of the profilers will reflect the change and explicitly list out the json container structure for each profiler. Thanks!
